"""
clustering.py

Fleet conformance clustering.

Reads conformance_log.csv (produced by fracture run-all or
scripts/05_generate_clustering_data.py) and groups pipelines
into HEALTHY / DRIFTING / CRITICAL clusters using k-Means and DBSCAN.

Validates cluster quality against ground truth labels using ARI
(Adjusted Rand Index). ARI > 0.7 is good. ARI > 0.5 is acceptable.

Feature vector per pipeline (computed from 7+ days of runs):
  mean_score       average final_score across days
  min_score        worst single day (catches intermittent failures)
  drift_rate       slope of score over time (negative = declining)
  variance_cv      daily score variance
  mean_gap         average bilateral gap (minutes)
  gap_trend_flag   1 if gap widening, 0 otherwise
  completeness     mean completeness_score
  seq_fitness_mean mean sequence_fitness

Usage:
  python clustering.py
  python clustering.py --csv path/to/conformance_log.csv
  python clustering.py --k 4 --show-features
"""

import argparse
import sys
import warnings
from pathlib import Path

import numpy as np
import pandas as pd
from sklearn.cluster import KMeans, DBSCAN
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import adjusted_rand_score, silhouette_score

warnings.filterwarnings('ignore')


# ── Feature engineering ───────────────────────────────────────────────────────

def build_features(df: pd.DataFrame) -> pd.DataFrame:
    """
    Build one feature vector per pipeline from conformance log.

    Two modes — automatically chosen based on CSV contents:

    Mode 1 — Pre-computed (preferred):
      fracture run now computes temporal features at run time and writes
      them to the CSV: temporal_variance_cv, drift_rate_per_day,
      score_range, mean_score_historical, min_score_historical.
      clustering.py reads these directly — no recalculation.

    Mode 2 — Recomputed (fallback):
      If temporal features are absent (old CSV, or generated by
      05_generate_clustering_data.py which does not call the CLI),
      clustering.py computes them from the raw daily scores.
      Same result, just done here instead of at run time.

    Why pre-computation at run time is better:
      - Single source of truth
      - Features available in fracture explain output
      - clustering.py becomes simpler
      - fracture status can show drift_rate directly
    """
    df = df.copy()
    for col in ['final_score', 'sequence_fitness', 'timing_score',
                'completeness_score', 'variance_cv']:
        df[col] = pd.to_numeric(df[col], errors='coerce')
    df['bilateral_gap'] = pd.to_numeric(df['bilateral_gap_minutes'], errors='coerce')
    df['run_date']      = pd.to_datetime(df['run_date'], format='%Y%m%d', errors='coerce')

    # Check if pre-computed temporal features exist in CSV
    has_precomputed = (
        'temporal_variance_cv' in df.columns and
        df['temporal_variance_cv'].notna().any()
    )

    features = []

    for pid, group in df.groupby('pipeline_id'):
        group  = group.sort_values('run_date')
        scores = group['final_score'].dropna().values

        if len(scores) < 2:
            continue

        # Gap features (always computed from raw data — gap history in CSV)
        gaps     = group['bilateral_gap'].dropna()
        mean_gap = float(gaps.mean()) if len(gaps) > 0 else 0.0
        gap_trend = 0.0
        gap_drift = 0.0
        if len(gaps) >= 3:
            gap_slope = np.polyfit(np.arange(len(gaps)), gaps.values, 1)[0]
            gap_trend = 1.0 if gap_slope > 0.5 else 0.0
        if len(gaps) >= 5:
            gap_drift = float(np.polyfit(range(len(gaps)), gaps.values, 1)[0])

        if has_precomputed:
            # Mode 1: use features computed by fracture run at run time
            # Take the most recent non-null values
            latest = group.dropna(subset=['temporal_variance_cv']).iloc[-1]                      if 'temporal_variance_cv' in group.columns else group.iloc[-1]

            def safe(col, default=0.0):
                v = latest.get(col, default)
                return float(v) if v not in ('', None) and str(v) != 'nan' else default

            row = {
                'pipeline_id':  pid,
                'mean_score':   safe('mean_score_historical',
                                     float(np.mean(scores))),
                'min_score':    safe('min_score_historical',
                                     float(np.min(scores))),
                'drift_rate':   safe('drift_rate_per_day'),
                'variance_cv':  safe('temporal_variance_cv'),
                'score_range':  safe('score_range',
                                     float(np.max(scores) - np.min(scores))),
                'mean_gap':     mean_gap,
                'gap_drift':    gap_drift,
                'gap_trend_flag': gap_trend,
                'completeness': float(group['completeness_score'].mean()),
                'seq_fitness':  float(group['sequence_fitness'].mean()),
                'expected_cluster': group['expected_cluster'].iloc[0]
                                    if 'expected_cluster' in group.columns else 'UNKNOWN',
                'archetype':    group['archetype'].iloc[0]
                                if 'archetype' in group.columns else 'unknown',
                'n_days':       len(scores),
                'feature_source': 'precomputed',
            }
        else:
            # Mode 2: compute from raw daily scores (fallback)
            x          = np.arange(len(scores))
            drift_rate = float(np.polyfit(x, scores, 1)[0]) if len(scores) >= 3 else 0.0
            scores_std = float(np.std(scores))
            scores_mean = float(np.mean(scores))
            temporal_cv = scores_std / scores_mean if scores_mean > 0 else 0.0
            score_range = float(np.max(scores) - np.min(scores))

            row = {
                'pipeline_id':  pid,
                'mean_score':   float(np.mean(scores)),
                'min_score':    float(np.min(scores)),
                'drift_rate':   drift_rate,
                'variance_cv':  temporal_cv,
                'score_range':  score_range,
                'mean_gap':     mean_gap,
                'gap_drift':    gap_drift,
                'gap_trend_flag': gap_trend,
                'completeness': float(group['completeness_score'].mean()),
                'seq_fitness':  float(group['sequence_fitness'].mean()),
                'expected_cluster': group['expected_cluster'].iloc[0]
                                    if 'expected_cluster' in group.columns else 'UNKNOWN',
                'archetype':    group['archetype'].iloc[0]
                                if 'archetype' in group.columns else 'unknown',
                'n_days':       len(scores),
                'feature_source': 'recomputed',
            }

        features.append(row)

    result_df = pd.DataFrame(features)
    if len(result_df) > 0 and 'feature_source' in result_df.columns:
        sources = result_df['feature_source'].value_counts().to_dict()
        if sources.get('precomputed', 0) > 0:
            print(f"  Features: {sources.get('precomputed',0)} pre-computed "
                  f"(from fracture run), "
                  f"{sources.get('recomputed',0)} recomputed (from CSV history)")
    return result_df


FEATURE_COLS = [
    'mean_score', 'min_score', 'drift_rate', 'variance_cv',
    'score_range', 'mean_gap', 'gap_drift', 'completeness', 'seq_fitness',
]

CLUSTER_NAMES = {0: 'HEALTHY', 1: 'DRIFTING', 2: 'CRITICAL'}


# ── Clustering ────────────────────────────────────────────────────────────────

def run_kmeans(X_scaled: np.ndarray, k: int = 3) -> np.ndarray:
    """
    k-Means clustering on the feature matrix.

    k=3 maps to HEALTHY / DRIFTING / CRITICAL.
    Uses multiple initialisations (n_init=20) for stability.
    """
    km = KMeans(n_clusters=k, n_init=20, random_state=42)
    return km.fit_predict(X_scaled)


def run_dbscan(X_scaled: np.ndarray) -> np.ndarray:
    """
    DBSCAN for anomaly detection.

    Pipelines in dense clusters = expected behaviour.
    Pipelines labelled -1 (noise) = anomalies requiring investigation.
    eps and min_samples tuned for typical fleet sizes (20-100 pipelines).
    """
    db = DBSCAN(eps=1.2, min_samples=2)
    return db.fit_predict(X_scaled)


def align_clusters_to_labels(labels: np.ndarray,
                              ground_truth: np.ndarray,
                              cluster_names: dict) -> dict:
    """
    k-Means assigns arbitrary cluster numbers (0, 1, 2).
    Map each cluster number to the ground truth label it best matches.
    """
    from collections import Counter
    mapping = {}
    for cluster_id in np.unique(labels):
        if cluster_id == -1:
            mapping[cluster_id] = 'ANOMALY'
            continue
        # Most common ground truth label for this cluster
        gt_in_cluster = ground_truth[labels == cluster_id]
        most_common = Counter(gt_in_cluster).most_common(1)[0][0]
        mapping[cluster_id] = most_common
    return mapping


# ── Main ──────────────────────────────────────────────────────────────────────

def main(csv_path: str = 'conformance_log.csv',
         k: int = 3,
         show_features: bool = False):

    # ── Load data ─────────────────────────────────────────────────────────
    path = Path(csv_path)
    if not path.exists():
        print(f"✗  {csv_path} not found.")
        print(f"   Run: python scripts/05_generate_clustering_data.py --days 7")
        sys.exit(1)

    df = pd.read_csv(path)
    print()
    print("FRACTURE — Fleet Clustering")
    print("═" * 65)
    print(f"  CSV           : {csv_path}")
    print(f"  Total rows    : {len(df)}")
    print(f"  Pipelines     : {df['pipeline_id'].nunique()}")
    print(f"  Days of data  : {df['run_date'].nunique()}")
    print(f"  k (clusters)  : {k}")

    # ── Build features ────────────────────────────────────────────────────
    feat_df = build_features(df)
    print(f"  Feature rows  : {len(feat_df)}")
    print()

    if show_features:
        print("  Feature matrix preview:")
        print(feat_df[['pipeline_id'] + FEATURE_COLS].to_string(index=False))
        print()

    X = feat_df[FEATURE_COLS].values
    scaler = StandardScaler()
    X_scaled = scaler.fit_transform(X)

    # ── k-Means ───────────────────────────────────────────────────────────
    km_labels = run_kmeans(X_scaled, k=k)
    feat_df['kmeans_cluster'] = km_labels

    # Silhouette score (cluster quality, -1 to 1, higher is better)
    sil = silhouette_score(X_scaled, km_labels) if len(np.unique(km_labels)) > 1 else 0.0

    # ARI against ground truth (if available)
    has_gt = 'expected_cluster' in feat_df.columns and \
             (feat_df['expected_cluster'] != 'UNKNOWN').all()
    ari = 0.0
    if has_gt:
        label_map = {'HEALTHY': 0, 'DRIFTING': 1, 'CRITICAL': 2}
        gt_numeric = feat_df['expected_cluster'].map(label_map).fillna(-1).values
        ari = adjusted_rand_score(gt_numeric, km_labels)

    # Align cluster numbers to meaningful names
    if has_gt:
        cluster_map = align_clusters_to_labels(
            km_labels, feat_df['expected_cluster'].values, CLUSTER_NAMES
        )
    else:
        # Without ground truth: assign by cluster centroids
        # Lowest mean_score = CRITICAL, highest = HEALTHY
        centroids = {cid: X_scaled[km_labels == cid].mean(axis=0)
                     for cid in np.unique(km_labels)}
        # Feature 0 = mean_score (after scaling, higher = better)
        sorted_clusters = sorted(centroids, key=lambda c: centroids[c][0], reverse=True)
        names = ['HEALTHY', 'DRIFTING', 'CRITICAL']
        cluster_map = {c: names[i] for i, c in enumerate(sorted_clusters)}

    feat_df['cluster_name'] = feat_df['kmeans_cluster'].map(cluster_map)

    # ── DBSCAN ────────────────────────────────────────────────────────────
    db_labels = run_dbscan(X_scaled)
    feat_df['dbscan_label'] = db_labels
    n_anomalies = (db_labels == -1).sum()

    # ── Print results ─────────────────────────────────────────────────────
    print("  k-Means clustering results:")
    print()

    for cluster_name in ['HEALTHY', 'DRIFTING', 'CRITICAL']:
        subset = feat_df[feat_df['cluster_name'] == cluster_name]
        if len(subset) == 0:
            continue
        print(f"  ── {cluster_name} ({len(subset)} pipelines) ──────────────────")
        print(f"     mean_score  : {subset['mean_score'].mean():.3f}")
        print(f"     min_score   : {subset['min_score'].mean():.3f}")
        print(f"     drift_rate  : {subset['drift_rate'].mean():+.4f}/day")
        print(f"     mean_gap    : {subset['mean_gap'].mean():.1f} min")
        print(f"     completeness: {subset['completeness'].mean():.3f}")
        print(f"     seq_fitness : {subset['seq_fitness'].mean():.3f}")
        print()
        for _, row in subset.iterrows():
            gt  = f"(GT:{row['expected_cluster']})" if has_gt else ''
            match = '✓' if not has_gt or row['expected_cluster'] == row['cluster_name'] else '✗'
            print(f"     {match} {row['pipeline_id']:<30} {gt}")
        print()

    print(f"  Silhouette score : {sil:.3f}  (higher = tighter clusters)")
    if has_gt:
        print(f"  ARI vs ground truth: {ari:.3f}  ", end='')
        if ari > 0.7:
            print("(good — clusters match expected behaviour)")
        elif ari > 0.5:
            print("(acceptable — some misassignments)")
        else:
            print("(low — features may need more history)")
    print()

    if n_anomalies > 0:
        print(f"  DBSCAN anomalies ({n_anomalies} pipelines):")
        anomalies = feat_df[feat_df['dbscan_label'] == -1]
        for _, row in anomalies.iterrows():
            print(f"    ⚠  {row['pipeline_id']:<30} score={row['mean_score']:.2f}  "
                  f"gap={row['mean_gap']:.0f}min")
        print()
        print("  Anomalies are outside all dense clusters.")
        print("  They warrant manual investigation — unusual behaviour.")
    else:
        print("  DBSCAN: no anomalies detected.")
    print()

    # ── Save results ──────────────────────────────────────────────────────
    out_path = Path('cluster_assignments.csv')
    feat_df[['pipeline_id','cluster_name','kmeans_cluster','dbscan_label',
             'mean_score','min_score','drift_rate','mean_gap','completeness',
             'expected_cluster','archetype']].to_csv(out_path, index=False)
    print(f"  Saved → {out_path}")
    print()
    print("  Next: python report.py")
    print("═" * 65)

    return feat_df, ari, sil


if __name__ == '__main__':
    parser = argparse.ArgumentParser(prog='clustering.py')
    parser.add_argument('--csv',           default='conformance_log.csv')
    parser.add_argument('--k',    type=int, default=3)
    parser.add_argument('--show-features', action='store_true')
    args = parser.parse_args()
    main(args.csv, args.k, args.show_features)
